/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildingsIndexRouteImport } from './routes/buildings/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as BuildingsNewRouteImport } from './routes/buildings/new'
import { Route as BuildingsBuildingIdRouteImport } from './routes/buildings/$buildingId'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiRevalidateRouteImport } from './routes/api/revalidate'
import { Route as ApiFormCacheRouteImport } from './routes/api/form-cache'
import { Route as ApiBuildingsRouteImport } from './routes/api/buildings'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as BuildingsEditBuildingIdRouteImport } from './routes/buildings/edit.$buildingId'
import { Route as ApiR2DevSplatRouteImport } from './routes/api/r2-dev.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsIndexRoute = BuildingsIndexRouteImport.update({
  id: '/buildings/',
  path: '/buildings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsNewRoute = BuildingsNewRouteImport.update({
  id: '/buildings/new',
  path: '/buildings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsBuildingIdRoute = BuildingsBuildingIdRouteImport.update({
  id: '/buildings/$buildingId',
  path: '/buildings/$buildingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRevalidateRoute = ApiRevalidateRouteImport.update({
  id: '/api/revalidate',
  path: '/api/revalidate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormCacheRoute = ApiFormCacheRouteImport.update({
  id: '/api/form-cache',
  path: '/api/form-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildingsRoute = ApiBuildingsRouteImport.update({
  id: '/api/buildings',
  path: '/api/buildings',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsEditBuildingIdRoute = BuildingsEditBuildingIdRouteImport.update({
  id: '/buildings/edit/$buildingId',
  path: '/buildings/edit/$buildingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiR2DevSplatRoute = ApiR2DevSplatRouteImport.update({
  id: '/api/r2-dev/$',
  path: '/api/r2-dev/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/buildings': typeof ApiBuildingsRoute
  '/api/form-cache': typeof ApiFormCacheRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/api/upload': typeof ApiUploadRoute
  '/buildings/$buildingId': typeof BuildingsBuildingIdRoute
  '/buildings/new': typeof BuildingsNewRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/buildings/': typeof BuildingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/r2-dev/$': typeof ApiR2DevSplatRoute
  '/buildings/edit/$buildingId': typeof BuildingsEditBuildingIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/buildings': typeof ApiBuildingsRoute
  '/api/form-cache': typeof ApiFormCacheRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/api/upload': typeof ApiUploadRoute
  '/buildings/$buildingId': typeof BuildingsBuildingIdRoute
  '/buildings/new': typeof BuildingsNewRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/buildings': typeof BuildingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/r2-dev/$': typeof ApiR2DevSplatRoute
  '/buildings/edit/$buildingId': typeof BuildingsEditBuildingIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/buildings': typeof ApiBuildingsRoute
  '/api/form-cache': typeof ApiFormCacheRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/api/upload': typeof ApiUploadRoute
  '/buildings/$buildingId': typeof BuildingsBuildingIdRoute
  '/buildings/new': typeof BuildingsNewRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/buildings/': typeof BuildingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/r2-dev/$': typeof ApiR2DevSplatRoute
  '/buildings/edit/$buildingId': typeof BuildingsEditBuildingIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/buildings'
    | '/api/form-cache'
    | '/api/revalidate'
    | '/api/upload'
    | '/buildings/$buildingId'
    | '/buildings/new'
    | '/demo/better-auth'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/buildings/'
    | '/api/auth/$'
    | '/api/r2-dev/$'
    | '/buildings/edit/$buildingId'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/buildings'
    | '/api/form-cache'
    | '/api/revalidate'
    | '/api/upload'
    | '/buildings/$buildingId'
    | '/buildings/new'
    | '/demo/better-auth'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/buildings'
    | '/api/auth/$'
    | '/api/r2-dev/$'
    | '/buildings/edit/$buildingId'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/api/buildings'
    | '/api/form-cache'
    | '/api/revalidate'
    | '/api/upload'
    | '/buildings/$buildingId'
    | '/buildings/new'
    | '/demo/better-auth'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/buildings/'
    | '/api/auth/$'
    | '/api/r2-dev/$'
    | '/buildings/edit/$buildingId'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBuildingsRoute: typeof ApiBuildingsRoute
  ApiFormCacheRoute: typeof ApiFormCacheRoute
  ApiRevalidateRoute: typeof ApiRevalidateRoute
  ApiUploadRoute: typeof ApiUploadRoute
  BuildingsBuildingIdRoute: typeof BuildingsBuildingIdRoute
  BuildingsNewRoute: typeof BuildingsNewRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  BuildingsIndexRoute: typeof BuildingsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiR2DevSplatRoute: typeof ApiR2DevSplatRoute
  BuildingsEditBuildingIdRoute: typeof BuildingsEditBuildingIdRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings/': {
      id: '/buildings/'
      path: '/buildings'
      fullPath: '/buildings/'
      preLoaderRoute: typeof BuildingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings/new': {
      id: '/buildings/new'
      path: '/buildings/new'
      fullPath: '/buildings/new'
      preLoaderRoute: typeof BuildingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings/$buildingId': {
      id: '/buildings/$buildingId'
      path: '/buildings/$buildingId'
      fullPath: '/buildings/$buildingId'
      preLoaderRoute: typeof BuildingsBuildingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/revalidate': {
      id: '/api/revalidate'
      path: '/api/revalidate'
      fullPath: '/api/revalidate'
      preLoaderRoute: typeof ApiRevalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/form-cache': {
      id: '/api/form-cache'
      path: '/api/form-cache'
      fullPath: '/api/form-cache'
      preLoaderRoute: typeof ApiFormCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/buildings': {
      id: '/api/buildings'
      path: '/api/buildings'
      fullPath: '/api/buildings'
      preLoaderRoute: typeof ApiBuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings/edit/$buildingId': {
      id: '/buildings/edit/$buildingId'
      path: '/buildings/edit/$buildingId'
      fullPath: '/buildings/edit/$buildingId'
      preLoaderRoute: typeof BuildingsEditBuildingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r2-dev/$': {
      id: '/api/r2-dev/$'
      path: '/api/r2-dev/$'
      fullPath: '/api/r2-dev/$'
      preLoaderRoute: typeof ApiR2DevSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBuildingsRoute: ApiBuildingsRoute,
  ApiFormCacheRoute: ApiFormCacheRoute,
  ApiRevalidateRoute: ApiRevalidateRoute,
  ApiUploadRoute: ApiUploadRoute,
  BuildingsBuildingIdRoute: BuildingsBuildingIdRoute,
  BuildingsNewRoute: BuildingsNewRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  BuildingsIndexRoute: BuildingsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiR2DevSplatRoute: ApiR2DevSplatRoute,
  BuildingsEditBuildingIdRoute: BuildingsEditBuildingIdRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
