/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms/index'
import { Route as BuildingsIndexRouteImport } from './routes/buildings/index'
import { Route as RoomsNewRouteImport } from './routes/rooms/new'
import { Route as RoomsRoomSlugRouteImport } from './routes/rooms/$roomSlug'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as BuildingsNewRouteImport } from './routes/buildings/new'
import { Route as BuildingsBuildingslugRouteImport } from './routes/buildings/$buildingslug'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiRoomsRouteImport } from './routes/api/rooms'
import { Route as ApiRevalidateRouteImport } from './routes/api/revalidate'
import { Route as ApiFormCacheRouteImport } from './routes/api/form-cache'
import { Route as ApiBuildingsRouteImport } from './routes/api/buildings'
import { Route as RoomsEditRoomSlugRouteImport } from './routes/rooms/edit.$roomSlug'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as BuildingsEditBuildingSlugRouteImport } from './routes/buildings/edit.$buildingSlug'
import { Route as ApiR2DevSplatRouteImport } from './routes/api/r2-dev.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsIndexRoute = BuildingsIndexRouteImport.update({
  id: '/buildings/',
  path: '/buildings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsNewRoute = RoomsNewRouteImport.update({
  id: '/rooms/new',
  path: '/rooms/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomSlugRoute = RoomsRoomSlugRouteImport.update({
  id: '/rooms/$roomSlug',
  path: '/rooms/$roomSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsNewRoute = BuildingsNewRouteImport.update({
  id: '/buildings/new',
  path: '/buildings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsBuildingslugRoute = BuildingsBuildingslugRouteImport.update({
  id: '/buildings/$buildingslug',
  path: '/buildings/$buildingslug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsRoute = ApiRoomsRouteImport.update({
  id: '/api/rooms',
  path: '/api/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRevalidateRoute = ApiRevalidateRouteImport.update({
  id: '/api/revalidate',
  path: '/api/revalidate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormCacheRoute = ApiFormCacheRouteImport.update({
  id: '/api/form-cache',
  path: '/api/form-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildingsRoute = ApiBuildingsRouteImport.update({
  id: '/api/buildings',
  path: '/api/buildings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsEditRoomSlugRoute = RoomsEditRoomSlugRouteImport.update({
  id: '/rooms/edit/$roomSlug',
  path: '/rooms/edit/$roomSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsEditBuildingSlugRoute =
  BuildingsEditBuildingSlugRouteImport.update({
    id: '/buildings/edit/$buildingSlug',
    path: '/buildings/edit/$buildingSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiR2DevSplatRoute = ApiR2DevSplatRouteImport.update({
  id: '/api/r2-dev/$',
  path: '/api/r2-dev/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/buildings': typeof ApiBuildingsRoute
  '/api/form-cache': typeof ApiFormCacheRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/api/rooms': typeof ApiRoomsRoute
  '/api/upload': typeof ApiUploadRoute
  '/buildings/$buildingslug': typeof BuildingsBuildingslugRoute
  '/buildings/new': typeof BuildingsNewRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/rooms/$roomSlug': typeof RoomsRoomSlugRoute
  '/rooms/new': typeof RoomsNewRoute
  '/buildings/': typeof BuildingsIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/r2-dev/$': typeof ApiR2DevSplatRoute
  '/buildings/edit/$buildingSlug': typeof BuildingsEditBuildingSlugRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/rooms/edit/$roomSlug': typeof RoomsEditRoomSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/buildings': typeof ApiBuildingsRoute
  '/api/form-cache': typeof ApiFormCacheRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/api/rooms': typeof ApiRoomsRoute
  '/api/upload': typeof ApiUploadRoute
  '/buildings/$buildingslug': typeof BuildingsBuildingslugRoute
  '/buildings/new': typeof BuildingsNewRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/rooms/$roomSlug': typeof RoomsRoomSlugRoute
  '/rooms/new': typeof RoomsNewRoute
  '/buildings': typeof BuildingsIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/r2-dev/$': typeof ApiR2DevSplatRoute
  '/buildings/edit/$buildingSlug': typeof BuildingsEditBuildingSlugRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/rooms/edit/$roomSlug': typeof RoomsEditRoomSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/buildings': typeof ApiBuildingsRoute
  '/api/form-cache': typeof ApiFormCacheRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/api/rooms': typeof ApiRoomsRoute
  '/api/upload': typeof ApiUploadRoute
  '/buildings/$buildingslug': typeof BuildingsBuildingslugRoute
  '/buildings/new': typeof BuildingsNewRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/rooms/$roomSlug': typeof RoomsRoomSlugRoute
  '/rooms/new': typeof RoomsNewRoute
  '/buildings/': typeof BuildingsIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/r2-dev/$': typeof ApiR2DevSplatRoute
  '/buildings/edit/$buildingSlug': typeof BuildingsEditBuildingSlugRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/rooms/edit/$roomSlug': typeof RoomsEditRoomSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/buildings'
    | '/api/form-cache'
    | '/api/revalidate'
    | '/api/rooms'
    | '/api/upload'
    | '/buildings/$buildingslug'
    | '/buildings/new'
    | '/demo/better-auth'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/rooms/$roomSlug'
    | '/rooms/new'
    | '/buildings/'
    | '/rooms/'
    | '/api/auth/$'
    | '/api/r2-dev/$'
    | '/buildings/edit/$buildingSlug'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/rooms/edit/$roomSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/buildings'
    | '/api/form-cache'
    | '/api/revalidate'
    | '/api/rooms'
    | '/api/upload'
    | '/buildings/$buildingslug'
    | '/buildings/new'
    | '/demo/better-auth'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/rooms/$roomSlug'
    | '/rooms/new'
    | '/buildings'
    | '/rooms'
    | '/api/auth/$'
    | '/api/r2-dev/$'
    | '/buildings/edit/$buildingSlug'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/rooms/edit/$roomSlug'
  id:
    | '__root__'
    | '/'
    | '/api/buildings'
    | '/api/form-cache'
    | '/api/revalidate'
    | '/api/rooms'
    | '/api/upload'
    | '/buildings/$buildingslug'
    | '/buildings/new'
    | '/demo/better-auth'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/rooms/$roomSlug'
    | '/rooms/new'
    | '/buildings/'
    | '/rooms/'
    | '/api/auth/$'
    | '/api/r2-dev/$'
    | '/buildings/edit/$buildingSlug'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/rooms/edit/$roomSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBuildingsRoute: typeof ApiBuildingsRoute
  ApiFormCacheRoute: typeof ApiFormCacheRoute
  ApiRevalidateRoute: typeof ApiRevalidateRoute
  ApiRoomsRoute: typeof ApiRoomsRoute
  ApiUploadRoute: typeof ApiUploadRoute
  BuildingsBuildingslugRoute: typeof BuildingsBuildingslugRoute
  BuildingsNewRoute: typeof BuildingsNewRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  RoomsRoomSlugRoute: typeof RoomsRoomSlugRoute
  RoomsNewRoute: typeof RoomsNewRoute
  BuildingsIndexRoute: typeof BuildingsIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiR2DevSplatRoute: typeof ApiR2DevSplatRoute
  BuildingsEditBuildingSlugRoute: typeof BuildingsEditBuildingSlugRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  RoomsEditRoomSlugRoute: typeof RoomsEditRoomSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings/': {
      id: '/buildings/'
      path: '/buildings'
      fullPath: '/buildings/'
      preLoaderRoute: typeof BuildingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/new': {
      id: '/rooms/new'
      path: '/rooms/new'
      fullPath: '/rooms/new'
      preLoaderRoute: typeof RoomsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomSlug': {
      id: '/rooms/$roomSlug'
      path: '/rooms/$roomSlug'
      fullPath: '/rooms/$roomSlug'
      preLoaderRoute: typeof RoomsRoomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings/new': {
      id: '/buildings/new'
      path: '/buildings/new'
      fullPath: '/buildings/new'
      preLoaderRoute: typeof BuildingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings/$buildingslug': {
      id: '/buildings/$buildingslug'
      path: '/buildings/$buildingslug'
      fullPath: '/buildings/$buildingslug'
      preLoaderRoute: typeof BuildingsBuildingslugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms': {
      id: '/api/rooms'
      path: '/api/rooms'
      fullPath: '/api/rooms'
      preLoaderRoute: typeof ApiRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/revalidate': {
      id: '/api/revalidate'
      path: '/api/revalidate'
      fullPath: '/api/revalidate'
      preLoaderRoute: typeof ApiRevalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/form-cache': {
      id: '/api/form-cache'
      path: '/api/form-cache'
      fullPath: '/api/form-cache'
      preLoaderRoute: typeof ApiFormCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/buildings': {
      id: '/api/buildings'
      path: '/api/buildings'
      fullPath: '/api/buildings'
      preLoaderRoute: typeof ApiBuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/edit/$roomSlug': {
      id: '/rooms/edit/$roomSlug'
      path: '/rooms/edit/$roomSlug'
      fullPath: '/rooms/edit/$roomSlug'
      preLoaderRoute: typeof RoomsEditRoomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings/edit/$buildingSlug': {
      id: '/buildings/edit/$buildingSlug'
      path: '/buildings/edit/$buildingSlug'
      fullPath: '/buildings/edit/$buildingSlug'
      preLoaderRoute: typeof BuildingsEditBuildingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r2-dev/$': {
      id: '/api/r2-dev/$'
      path: '/api/r2-dev/$'
      fullPath: '/api/r2-dev/$'
      preLoaderRoute: typeof ApiR2DevSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBuildingsRoute: ApiBuildingsRoute,
  ApiFormCacheRoute: ApiFormCacheRoute,
  ApiRevalidateRoute: ApiRevalidateRoute,
  ApiRoomsRoute: ApiRoomsRoute,
  ApiUploadRoute: ApiUploadRoute,
  BuildingsBuildingslugRoute: BuildingsBuildingslugRoute,
  BuildingsNewRoute: BuildingsNewRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  RoomsRoomSlugRoute: RoomsRoomSlugRoute,
  RoomsNewRoute: RoomsNewRoute,
  BuildingsIndexRoute: BuildingsIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiR2DevSplatRoute: ApiR2DevSplatRoute,
  BuildingsEditBuildingSlugRoute: BuildingsEditBuildingSlugRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  RoomsEditRoomSlugRoute: RoomsEditRoomSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
